[package]
name = "hyperdb"
version = "0.1.0"
edition = "2021"
authors = ["Afaan Bilal <hello@afaan.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
