[package]
name = "hyperdb"
version = "0.2.0"
edition = "2021"
authors = ["Afaan Bilal <hello@afaan.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
jsonwebtoken = "8.2.0"
serde = "1.0.152"
serde_json = "1.0.91"
